# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f67ed033bd15f9ce6633640c8938dfb12d37f5ebb661e438abbd7ace91ee6324bd818af4e2b9db7001de4f8bf55b5acaadb2b9d9c3574b3f7419c005a605185b

test:
  secret_key_base: a53b89b84397f9f92a59a19676f3299a10d745c223b1340cdf01ec848bed2187ca0f853ad7afbbaf2f35814e4ce1404c9d194361dc52d096e1ce713875c98d5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
